naomi-lgbt/melody-iuvo

.eslintrc.json, src/commands/assets.ts, src/config/AssetData.ts, src/interfaces/Asset.ts, src/modules/subcommands/assets/defaultAssetEmbed.ts, src/modules/subcommands/assets/handleAdventureAsset.ts, src/modules/subcommands/assets/handleEmoteAsset.ts, src/modules/subcommands/assets/handleKoikatsuAsset.ts, src/modules/subcommands/assets/handleOutfitAsset.ts, src/modules/subcommands/assets/handlePortraitAsset.ts, src/modules/subcommands/assets/handleReferenceAsset.ts, src/modules/subcommands/assets/handleTattooAsset.ts, src/utils/getAssetList.ts, src/utils/typeGuards.ts
=> feat: import asset bot

src/events/messageCreate.ts
=> fix: earn currency on messages

src/config/Currency.ts
=> chore: add holopin badge item

src/events/messageCreate.ts
=> feat: respond if melody is pinged

src/modules/processGithubIssues.ts
=> feat: send all issues at once

src/events/messageCreate.ts, src/modules/processGithubIssues.ts
=> feat: use stickers in messages

.nycrc.json, package.json, pnpm-lock.yaml, src/modules/subcommands/currency/handleCurrencyItem.ts, src/modules/subcommands/currency/handleCurrencyPurchase.ts, src/modules/subcommands/plural/handlePluralFront.ts, test/__mocks__/Database.mock.ts, test/commands/faq.spec.ts, test/commands/help.spec.ts, test/commands/naomi.spec.ts, test/commands/plural.spec.ts, test/modules/subcommands/currency/handleCurrencyCache.spec.ts, test/modules/subcommands/currency/handleCurrencyItem.spec.ts, test/modules/subcommands/currency/handleCurrencyPurchase.spec.ts, test/modules/subcommands/currency/handleCurrencySlots.spec.ts, test/modules/subcommands/currency/handleCurrencyWallet.spec.ts, test/modules/subcommands/currency/handleCurrencyWord.spec.ts, test/modules/subcommands/naomi/handleNaomiAsk.spec.ts, test/modules/subcommands/naomi/handleNaomiSays.spec.ts, test/modules/subcommands/plural/handlePluralCreate.spec.ts, test/modules/subcommands/plural/handlePluralDelete.spec.ts, test/modules/subcommands/plural/handlePluralFront.spec.ts
=> feat(tools): finish tests for commands

.github/workflows/code-ql.yml, .github/workflows/node-ci.yml, .nycrc.json, package.json, pnpm-lock.yaml, src/events/interactionCreate.ts, src/modules/generateLogs.ts, src/modules/messages/proxyPluralMessage.ts, src/modules/messages/pruneInactiveUsers.ts, src/utils/registerCommands.ts, test/__mocks__/Database.mock.ts, test/events/clientReady.spec.ts, test/events/interactionCreate.spec.ts, test/events/messageCreate.spec.ts, test/modules/createLogFile.spec.ts, test/modules/generateLogs.spec.ts, test/modules/logTicketMessage.spec.ts, test/modules/messages/proxyPluralMessage.spec.ts, test/modules/messages/pruneInactiveUsers.spec.ts, test/modules/messages/startTicketPost.spec.ts, test/modules/prefixHex.spec.ts, test/modules/processGithubIssues.spec.ts, test/utils/errorHandler.spec.ts, test/utils/getAssetList.spec.ts, test/utils/getRandomValue.spec.ts, test/utils/registerCommands.spec.ts
=> feat: utils, modules, and event tests

src/config/Intents.ts, src/events/autoModerationActionExecution.ts, src/index.ts, test/config/Intents.spec.ts, test/events/autoModerationActionExecution.spec.ts
=> feat: send a teasing message when automod is triggered

src/events/autoModerationActionExecution.ts, src/index.ts, src/interfaces/ExtendedClient.ts, test/events/autoModerationActionExecution.spec.ts
=> feat: add cooldown to automod trigger

src/commands/assets.ts, src/interfaces/Asset.ts, src/modules/subcommands/assets/handlePicrewAsset.ts, test/modules/subcommands/assets/handlePicrewAsset.spec.ts
=> feat: picrew assets

src/commands/assets.ts, src/config/Responses.ts, src/events/messageCreate.ts, test/config/Responses.spec.ts, test/events/messageCreate.spec.ts
=> feat: add infrastructure for customised replies to specific people

src/config/Responses.ts, src/events/autoModerationActionExecution.ts, test/events/autoModerationActionExecution.spec.ts
=> feat: custom responses for automod trigger

src/commands/assets.ts, src/config/Responses.ts, src/events/autoModerationActionExecution.ts, src/events/messageCreate.ts, src/modules/parseCutieRole.ts, test/config/Responses.spec.ts, test/modules/parseCutieRole.spec.ts
=> feat: custom partner responses

src/events/messageCreate.ts, test/events/messageCreate.spec.ts
=> fix: generate correct thanks response

.nycrc.json, src/events/interactionCreate.ts, src/events/messageCreate.ts, src/modules/buttons/processRoleButton.ts, src/modules/messages/postReactionRoles.ts, test/modules/buttons/processRoleButton.spec.ts, test/modules/messages/postReactionRoles.spec.ts
=> feat: support role buttons

.github/workflows/code-ql.yml, .github/workflows/deploy-coverage.yml, .github/workflows/node-ci.yml, package.json
=> chore: move to node 20

src/commands/assets.ts, src/interfaces/Asset.ts
=> feat: add erin to assets

src/events/messageCreate.ts
=> feat: heart react partner messages

src/events/messageCreate.ts, src/interfaces/ExtendedClient.ts, src/utils/validateEnv.ts, test/utils/validateEnv.spec.ts
=> feat: add venting channel feature

.nycrc.json, src/config/Intents.ts, src/events/voiceStateUpdate.ts, src/index.ts, src/utils/isOwner.ts, test/config/Intents.spec.ts, test/events/voiceStateUpdate.spec.ts, test/utils/isOwner.spec.ts
=> feat: notify when naomi streams

.nycrc.json, src/modules/subcommands/assets/handleAdventureAsset.ts, src/modules/subcommands/assets/handleEmoteAsset.ts, src/modules/subcommands/assets/handleKoikatsuAsset.ts, src/modules/subcommands/assets/handleOutfitAsset.ts, src/modules/subcommands/assets/handlePicrewAsset.ts, src/modules/subcommands/assets/handlePortraitAsset.ts
=> feat: display asset counts

src/modules/subcommands/assets/handlePortraitAsset.ts
=> fix: use correct key for portraits

src/commands/tarot.ts, src/config/TarotCards.ts, src/index.ts, src/interfaces/ExtendedClient.ts, src/interfaces/TarotCard.ts, test/commands/tarot.spec.ts, test/config/TarotCards.spec.ts
=> feat: tarot readings

src/commands/tarot.ts, test/commands/tarot.spec.ts
This was an order of operations issue.
Closes #XXXXX
=> fix: bug in tarot logic

src/utils/mountTwitch.ts
=> feat: include vod, handle null stream

src/utils/mountTwitch.ts
This PR fixes the issue where Twitch role pinging incorrectly tagged a user instead of the intended role.
Closes #91
=> fix: twitch role ping tagging

.nycrc.json, script/resetCurrency.ts, src/commands/queue.ts, src/config/Currency.ts, src/config/GameQueue.ts, test/modules/subcommands/currency/handleCurrencyItem.spec.ts, test/modules/subcommands/currency/handleCurrencyPurchase.spec.ts
=> feat: add stream rewards

package.json, pnpm-lock.yaml, src/events/clientReady.ts
=> feat: post daily donation reminder

src/commands/naomi.ts, src/config/Responses.ts, src/events/clientReady.ts, src/modules/buttons/questionAnswer.ts, src/modules/modals/processQuestionModal.ts, src/modules/processGithubIssues.ts, src/modules/subcommands/currency/handleCurrencyAward.ts, src/modules/subcommands/currency/handleCurrencyCache.ts, src/modules/subcommands/currency/handleCurrencyPurchase.ts, test/events/autoModerationActionExecution.spec.ts, test/events/messageCreate.spec.ts, test/modules/subcommands/currency/handleCurrencyAward.spec.ts, test/modules/subcommands/currency/handleCurrencyCache.spec.ts
I have found all the strings where Melody uses "Mistress" or "my Mistress", I have changed them to "Mama", "my Mama", or "Mama Naomi", based on feedback I can uniformize those
Closes #97
=> chore: change mistress to mama

src/utils/mountTwitch.ts
=> feat: update role, pin latest stream message

src/events/interactionCreate.ts, src/events/messageCreate.ts, src/modules/buttons/processComfortButton.ts, src/modules/messages/startComfortPost.ts, src/utils/loadSteam.ts, test/modules/buttons/processComfortButton.spec.ts, test/modules/messages/startComfortPost.spec.ts
=> feat: add comfort system

.github/workflows/node-ci.yml, package.json, src/commands/about.ts, src/index.ts, src/interfaces/ExtendedClient.ts, test/commands/about.spec.ts
=> feat: add about command

.github/workflows/deploy-coverage.yml
=> fix(tools): use the generate command for deployment

src/events/clientReady.ts, src/index.ts, src/interfaces/ExtendedClient.ts, src/utils/loadGeneralChannel.ts, src/utils/mountTwitch.ts, test/utils/loadGeneralChannel.spec.ts
=> feat: join and leave messages

src/server/serve.ts
=> fix: correct the kofi and patreon webhooks.

.nycrc.json, prisma/schema.prisma, src/commands/birthday.ts, src/config/BirthdayGifs.ts, src/events/clientReady.ts, src/modules/scheduleBirthdayPosts.ts, src/utils/getDatabaseRecord.ts, src/utils/validateDate.ts, test/commands/birthday.spec.ts, test/config/BirthdayGifs.spec.ts, test/modules/scheduleBirthdayPosts.spec.ts, test/utils/validateDate.spec.ts
=> feat: add birthday system

src/modules/scheduleBirthdayPosts.ts, test/modules/scheduleBirthdayPosts.spec.ts
This PR removes the daily error message sent by melody.
Closes #121
=> fix: no birthday error

src/modules/subcommands/assets/handleAdventureAsset.ts, src/modules/subcommands/assets/handleEmoteAsset.ts, src/modules/subcommands/assets/handleKoikatsuAsset.ts, src/modules/subcommands/assets/handleOutfitAsset.ts, src/modules/subcommands/assets/handlePortraitAsset.ts, src/utils/mountTwitch.ts
=> fix: asset and twitch notification formatting

src/commands/holopin.ts, test/commands/holopin.spec.ts
=> feat: add holopin command

.nycrc.json, src/config/Snippets.ts, src/contexts/snippet.ts, src/events/interactionCreate.ts, src/index.ts, src/interfaces/Context.ts, src/interfaces/ExtendedClient.ts, src/utils/loadContexts.ts, src/utils/registerCommands.ts, test/config/Snippets.spec.ts, test/contexts/snippet.spec.ts, test/events/interactionCreate.spec.ts, test/utils/loadContexts.spec.ts, test/utils/registerCommands.spec.ts
=> feat: add snippets context command

src/utils/loadGeneralChannel.ts
=> feat: fetch members on boot

src/commands/assets.ts, src/config/Responses.ts, src/events/autoModerationActionExecution.ts, src/events/messageCreate.ts, test/config/Responses.spec.ts, test/events/autoModerationActionExecution.spec.ts, test/events/messageCreate.spec.ts
=> feat: allow melody's responses to be randomised

src/utils/mountTwitch.ts
=> fix: twitch formatting

src/commands/bean.ts, src/events/clientReady.ts, src/events/messageCreate.ts, src/index.ts, src/interfaces/ExtendedClient.ts, test/commands/bean.spec.ts
=> feat: add bean command

src/modules/messages/pruneInactiveUsers.ts, test/events/messageCreate.spec.ts, test/modules/messages/pruneInactiveUsers.spec.ts
=> feat: upload prune users as attachment

src/modules/messages/pruneInactiveUsers.ts
=> feat: add filters to prune logic

src/modules/messages/pruneInactiveUsers.ts
=> fix: update filter names to reflect witch branding

.nycrc.json, prisma/schema.prisma, src/commands/initiate.ts, src/utils/getDatabaseRecord.ts, test/commands/initiate.spec.ts
=> feat: add initiate command

.nycrc.json, src/commands/assets.ts, src/commands/bean.ts, src/commands/initiate.ts, src/events/autoModerationActionExecution.ts, src/events/clientReady.ts, src/events/messageCreate.ts, src/index.ts, src/interfaces/ExtendedClient.ts, src/modules/getResponseKey.ts, src/modules/messages/pruneInactiveUsers.ts, src/modules/postQuestion.ts, src/modules/processGithubIssues.ts, src/modules/scheduleBirthdayPosts.ts, src/server/serve.ts, src/utils/loadDiscordCache.ts, src/utils/mountTwitch.ts, test/commands/bean.spec.ts, test/commands/initiate.spec.ts, test/events/autoModerationActionExecution.spec.ts, test/events/messageCreate.spec.ts, test/modules/getResponseKey.spec.ts, test/modules/messages/pruneInactiveUsers.spec.ts, test/modules/postQuestion.spec.ts, test/modules/scheduleBirthdayPosts.spec.ts
=> fix: cache all roles, improve caching structure

src/utils/loadDiscordCache.ts
=> fix: mount full cache at once to avoid undefined errors

src/utils/loadDiscordCache.ts
=> chore: update channel/role names

src/config/Questions.ts
It removes a question regarding the selling and buying of kidneys.
=> fix: remove dumb question

src/commands/initiate.ts, src/commands/training.ts, src/config/Training.ts, src/events/clientReady.ts, src/modules/announceCovenStats.ts, test/commands/initiate.spec.ts, test/commands/training.spec.ts, test/config/Training.spec.ts, test/modules/announceCovenStats.spec.ts
=> feat: add training system

.nycrc.json, src/events/messageCreate.ts, src/modules/messages/auditGuildsAndDatabase.ts, test/modules/messages/auditGuildsAndDatabase.spec.ts
=> feat: add system to audit bot's guilds and database records

src/index.ts
=> feat: delete user record on member leave

src/config/Currency.ts
=> chore: remove colour role item

src/modules/announceCovenStats.ts
=> chore: rename magic roles

src/events/messageCreate.ts
=> feat: no greetings for replies

.eslintrc.json, src/commands/bean.ts, src/commands/initiate.ts, src/commands/training.ts, src/events/autoModerationActionExecution.ts, src/events/clientReady.ts, src/events/messageCreate.ts, src/index.ts, src/interfaces/ExtendedClient.ts, src/modules/announceCovenStats.ts, src/modules/getDailyEventChange.ts, src/modules/getResponseKey.ts, src/modules/messages/auditGuildsAndDatabase.ts, src/modules/messages/pruneInactiveUsers.ts, src/modules/postQuestion.ts, src/modules/processGithubIssues.ts, src/modules/scheduleBirthdayPosts.ts, src/server/serve.ts, src/utils/loadDiscordCache.ts, src/utils/mountTwitch.ts
=> fix: allow bot to work without cached discord values

src/commands/bubbles.ts, src/events/messageCreate.ts, test/commands/bubbles.spec.ts
=> feat: add bubble wrap command

.nycrc.json, package.json, pnpm-lock.yaml, src/commands/minesweeper.ts, test/commands/minesweeper.spec.ts
=> feat: add minesweeper command

src/commands/bubbles.ts, test/commands/bubbles.spec.ts, test/commands/minesweeper.spec.ts
=> fix: bubbles should be 2000 long max

src/commands/about.ts, src/commands/birthday.ts, src/commands/game.ts, src/commands/holopin.ts, src/commands/queue.ts, src/commands/tarot.ts, src/commands/yokai.ts, src/contexts/snippet.ts, src/events/messageCreate.ts, src/interfaces/Context.ts, test/misc.spec.ts
=> chore: ignore everything in DMs

src/config/Tickets.ts
=> feat: update ticket role

src/server/serve.ts
=> feat: include reason for returning in appeal

.nycrc.json, src/events/messageCreate.ts, src/index.ts, src/modules/assignRoles.ts, src/utils/loadDiscordCache.ts, test/modules/assignRoles.spec.ts
=> feat: add automatic divider + member role assignment

src/commands/queue.ts, src/commands/schedule.ts, src/config/Currency.ts, src/config/GameQueue.ts, test/commands/schedule.spec.ts, test/config/GameQueue.spec.ts
=> feat: add schedule command for stream schedule

.gitignore, .knip.jsonc, calendar/.gitkeep, package.json, pnpm-lock.yaml, script/calendarAuth.ts, src/commands/calendar.ts, test/commands/calendar.spec.ts
=> feat: add calendar command

src/events/messageCreate.ts
If someone says sorry or thank you towards another bot, it shouldn't automatically try to thank you or sorry towards it. 
Closes #228
=> Fix: Try to prevent Melody thanking herself.

.nycrc.json, script/calendarAuth.ts, src/commands/assets.ts
=> feat: add button to download vrm

package.json, pnpm-lock.yaml, prisma/schema.prisma, src/commands/reminder.ts, src/events/clientReady.ts, test/commands/reminder.spec.ts
=> feat: build reminder system

.nycrc.json, src/commands/meeting.ts, src/commands/reminder.ts, test/commands/meeting.spec.ts
=> feat: add meeting system

src/events/autoModerationActionExecution.ts
The stickers that are outdated now due to not being a part of the server is removed from the code.
Closes #246
=> Chore: Removed Sticker

src/events/clientReady.ts
All it does it remove the schedule to post the donation reminder at noon every day. Nothing more. Nothing less. 
Closes #269
=> chore: remove daily reminder to donate

src/events/messageCreate.ts
=> fix: no autoresponse in partner channel

src/index.ts
=> feat: update welcome/goodbye messages

src/utils/loadDiscordCache.ts
=> fix: update role name

src/events/voiceStateUpdate.ts, src/interfaces/ExtendedClient.ts, src/utils/loadDiscordCache.ts
=> feat: add more voice channel notifications

src/events/messageCreate.ts, src/interfaces/ExtendedClient.ts, src/modules/messages/pruneInactiveUsers.ts, src/utils/loadDiscordCache.ts
=> feat: add supplicant role

prisma/schema.prisma, src/commands/reminder.ts, src/events/clientReady.ts
=> feat: allow naomi to remind other people through melody

src/commands/reminder.ts
=> fix: use correct variable scope

src/commands/assets.ts, src/commands/reloadJobs.ts, src/commands/reminder.ts, src/events/clientReady.ts, src/modules/processGithubIssues.ts, src/server/serve.ts, src/utils/errorHandler.ts, src/utils/loadDiscordCache.ts, test/utils/errorHandler.spec.ts
=> feat: include avatar + name in webhook

.nycrc.json, src/interfaces/ExtendedClient.ts, src/modules/processGithubIssues.ts, src/utils/loadDiscordCache.ts
=> feat: pipe mentorship issues to private channel

src/interfaces/GitHubPayloads.ts, src/server/github/generateIssueEmbed.ts, src/server/github/generatePullEmbed.ts
=> feat: improve the github logic

src/commands/todo.ts
It uses the code from the daily announcement to provide a way to list all of Naomi's tasks. I believe `editReply` is the preferred method to use in these commands as the other sub-commands use it. 
Closes #358
=> feat: create a todo list subcommand

.nycrc.json, src/events/clientReady.ts, src/interfaces/ExtendedClient.ts, src/modules/awakenMember.ts, src/utils/loadDiscordCache.ts, test/modules/awakenMember.spec.ts
=> feat: awakening system

src/commands/todo.ts
This should correct the minor oversight of having the list requiring a key that isn't found and shouldn't be there.  
Related to #358
=> fix: move todo list before key search

src/index.ts, src/interfaces/ExtendedClient.ts, src/utils/loadDiscordCache.ts
=> feat: welcome members AFTER they complete onboarding

.nycrc.json, src/config/Emotes.ts, src/config/ModerationCommands.ts, src/events/interactionCreate.ts, src/index.ts, src/interfaces/ExtendedClient.ts, src/modules/processModAction.ts, src/utils/loadDiscordCache.ts, src/utils/registerCommands.ts, src/utils/typeGuards.ts, test/config/Emotes.spec.ts, test/config/ModerationCommands.spec.ts, test/modules/processModAction.spec.ts, test/utils/registerCommands.spec.ts
=> feat: moderation

src/modules/awakenMember.ts
This removes bots from our list of members that can be awakened on the server. This was made in response to Melody awakening herself.
=> fix: bots will not become awakened

src/config/Github.ts
=> fix: don't post github actions that melody triggered

src/index.ts, src/modules/processModAction.ts
=> fix: message edit logic and ban limit
